// source: msg.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.sdk.MessagePb');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.sdk.SendClientInfoPb');

goog.forwardDeclare('proto.sdk.MessagePriority');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sdk.MessagePb = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sdk.MessagePb, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sdk.MessagePb.displayName = 'proto.sdk.MessagePb';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sdk.MessagePb.prototype.toObject = function(opt_includeInstance) {
  return proto.sdk.MessagePb.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sdk.MessagePb} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sdk.MessagePb.toObject = function(includeInstance, msg) {
  var f, obj = {
sendclient: (f = msg.getSendclient()) && proto.sdk.SendClientInfoPb.toObject(includeInstance, f),
messageid: jspb.Message.getFieldWithDefault(msg, 2, ""),
code: jspb.Message.getFieldWithDefault(msg, 3, ""),
msg: jspb.Message.getFieldWithDefault(msg, 4, ""),
data: jspb.Message.getFieldWithDefault(msg, 5, ""),
liveid: jspb.Message.getFieldWithDefault(msg, 6, ""),
timestamp: jspb.Message.getFieldWithDefault(msg, 7, 0),
priority: jspb.Message.getFieldWithDefault(msg, 8, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sdk.MessagePb}
 */
proto.sdk.MessagePb.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sdk.MessagePb;
  return proto.sdk.MessagePb.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sdk.MessagePb} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sdk.MessagePb}
 */
proto.sdk.MessagePb.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.sdk.SendClientInfoPb;
      reader.readMessage(value,proto.sdk.SendClientInfoPb.deserializeBinaryFromReader);
      msg.setSendclient(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessageid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setMsg(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setData(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setLiveid(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 8:
      var value = /** @type {!proto.sdk.MessagePriority} */ (reader.readEnum());
      msg.setPriority(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sdk.MessagePb.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sdk.MessagePb.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sdk.MessagePb} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sdk.MessagePb.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSendclient();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.sdk.SendClientInfoPb.serializeBinaryToWriter
    );
  }
  f = message.getMessageid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCode();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getMsg();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getData();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getLiveid();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getPriority();
  if (f !== 0.0) {
    writer.writeEnum(
      8,
      f
    );
  }
};


/**
 * optional SendClientInfoPb sendClient = 1;
 * @return {?proto.sdk.SendClientInfoPb}
 */
proto.sdk.MessagePb.prototype.getSendclient = function() {
  return /** @type{?proto.sdk.SendClientInfoPb} */ (
    jspb.Message.getWrapperField(this, proto.sdk.SendClientInfoPb, 1));
};


/**
 * @param {?proto.sdk.SendClientInfoPb|undefined} value
 * @return {!proto.sdk.MessagePb} returns this
*/
proto.sdk.MessagePb.prototype.setSendclient = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sdk.MessagePb} returns this
 */
proto.sdk.MessagePb.prototype.clearSendclient = function() {
  return this.setSendclient(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sdk.MessagePb.prototype.hasSendclient = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string messageId = 2;
 * @return {string}
 */
proto.sdk.MessagePb.prototype.getMessageid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.sdk.MessagePb} returns this
 */
proto.sdk.MessagePb.prototype.setMessageid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string code = 3;
 * @return {string}
 */
proto.sdk.MessagePb.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.sdk.MessagePb} returns this
 */
proto.sdk.MessagePb.prototype.setCode = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string msg = 4;
 * @return {string}
 */
proto.sdk.MessagePb.prototype.getMsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.sdk.MessagePb} returns this
 */
proto.sdk.MessagePb.prototype.setMsg = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string data = 5;
 * @return {string}
 */
proto.sdk.MessagePb.prototype.getData = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.sdk.MessagePb} returns this
 */
proto.sdk.MessagePb.prototype.setData = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string liveId = 6;
 * @return {string}
 */
proto.sdk.MessagePb.prototype.getLiveid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.sdk.MessagePb} returns this
 */
proto.sdk.MessagePb.prototype.setLiveid = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional int64 timestamp = 7;
 * @return {number}
 */
proto.sdk.MessagePb.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.sdk.MessagePb} returns this
 */
proto.sdk.MessagePb.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional MessagePriority priority = 8;
 * @return {!proto.sdk.MessagePriority}
 */
proto.sdk.MessagePb.prototype.getPriority = function() {
  return /** @type {!proto.sdk.MessagePriority} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {!proto.sdk.MessagePriority} value
 * @return {!proto.sdk.MessagePb} returns this
 */
proto.sdk.MessagePb.prototype.setPriority = function(value) {
  return jspb.Message.setProto3EnumField(this, 8, value);
};


