// source: msg.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.sdk.SendClientInfoPb');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sdk.SendClientInfoPb = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sdk.SendClientInfoPb, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sdk.SendClientInfoPb.displayName = 'proto.sdk.SendClientInfoPb';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sdk.SendClientInfoPb.prototype.toObject = function(opt_includeInstance) {
  return proto.sdk.SendClientInfoPb.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sdk.SendClientInfoPb} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sdk.SendClientInfoPb.toObject = function(includeInstance, msg) {
  var f, obj = {
nickname: jspb.Message.getFieldWithDefault(msg, 1, ""),
userid: jspb.Message.getFieldWithDefault(msg, 2, ""),
usertags: jspb.Message.getFieldWithDefault(msg, 3, ""),
isanchor: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
ismuted: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
istrigerswd: jspb.Message.getBooleanFieldWithDefault(msg, 6, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sdk.SendClientInfoPb}
 */
proto.sdk.SendClientInfoPb.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sdk.SendClientInfoPb;
  return proto.sdk.SendClientInfoPb.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sdk.SendClientInfoPb} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sdk.SendClientInfoPb}
 */
proto.sdk.SendClientInfoPb.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNickname(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUsertags(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsanchor(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsmuted(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIstrigerswd(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sdk.SendClientInfoPb.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sdk.SendClientInfoPb.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sdk.SendClientInfoPb} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sdk.SendClientInfoPb.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNickname();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUserid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUsertags();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getIsanchor();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getIsmuted();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getIstrigerswd();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
};


/**
 * optional string nickName = 1;
 * @return {string}
 */
proto.sdk.SendClientInfoPb.prototype.getNickname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.sdk.SendClientInfoPb} returns this
 */
proto.sdk.SendClientInfoPb.prototype.setNickname = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string userId = 2;
 * @return {string}
 */
proto.sdk.SendClientInfoPb.prototype.getUserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.sdk.SendClientInfoPb} returns this
 */
proto.sdk.SendClientInfoPb.prototype.setUserid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string userTags = 3;
 * @return {string}
 */
proto.sdk.SendClientInfoPb.prototype.getUsertags = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.sdk.SendClientInfoPb} returns this
 */
proto.sdk.SendClientInfoPb.prototype.setUsertags = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional bool isAnchor = 4;
 * @return {boolean}
 */
proto.sdk.SendClientInfoPb.prototype.getIsanchor = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sdk.SendClientInfoPb} returns this
 */
proto.sdk.SendClientInfoPb.prototype.setIsanchor = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional bool isMuted = 5;
 * @return {boolean}
 */
proto.sdk.SendClientInfoPb.prototype.getIsmuted = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sdk.SendClientInfoPb} returns this
 */
proto.sdk.SendClientInfoPb.prototype.setIsmuted = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool isTrigerSwd = 6;
 * @return {boolean}
 */
proto.sdk.SendClientInfoPb.prototype.getIstrigerswd = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sdk.SendClientInfoPb} returns this
 */
proto.sdk.SendClientInfoPb.prototype.setIstrigerswd = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


