// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: msg.proto

package sdk

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 添加：定义消息优先级枚举
type MessagePriority int32

const (
	MessagePriority_LOW  MessagePriority = 0 // 低优先级
	MessagePriority_HIGH MessagePriority = 1 // 高优先级
)

// Enum value maps for MessagePriority.
var (
	MessagePriority_name = map[int32]string{
		0: "LOW",
		1: "HIGH",
	}
	MessagePriority_value = map[string]int32{
		"LOW":  0,
		"HIGH": 1,
	}
)

func (x MessagePriority) Enum() *MessagePriority {
	p := new(MessagePriority)
	*p = x
	return p
}

func (x MessagePriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessagePriority) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_proto_enumTypes[0].Descriptor()
}

func (MessagePriority) Type() protoreflect.EnumType {
	return &file_msg_proto_enumTypes[0]
}

func (x MessagePriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessagePriority.Descriptor instead.
func (MessagePriority) EnumDescriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

type MessagePb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SendClient    *SendClientInfoPb      `protobuf:"bytes,1,opt,name=sendClient,proto3" json:"sendClient,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=messageId,proto3" json:"messageId,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          string                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	LiveId        string                 `protobuf:"bytes,6,opt,name=liveId,proto3" json:"liveId,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Priority      MessagePriority        `protobuf:"varint,8,opt,name=priority,proto3,enum=sdk.MessagePriority" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagePb) Reset() {
	*x = MessagePb{}
	mi := &file_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePb) ProtoMessage() {}

func (x *MessagePb) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePb.ProtoReflect.Descriptor instead.
func (*MessagePb) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

func (x *MessagePb) GetSendClient() *SendClientInfoPb {
	if x != nil {
		return x.SendClient
	}
	return nil
}

func (x *MessagePb) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessagePb) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MessagePb) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MessagePb) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *MessagePb) GetLiveId() string {
	if x != nil {
		return x.LiveId
	}
	return ""
}

func (x *MessagePb) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessagePb) GetPriority() MessagePriority {
	if x != nil {
		return x.Priority
	}
	return MessagePriority_LOW
}

type SendClientInfoPb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NickName      string                 `protobuf:"bytes,1,opt,name=nickName,proto3" json:"nickName,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	UserTags      string                 `protobuf:"bytes,3,opt,name=userTags,proto3" json:"userTags,omitempty"`
	IsAnchor      bool                   `protobuf:"varint,4,opt,name=isAnchor,proto3" json:"isAnchor,omitempty"`
	IsMuted       bool                   `protobuf:"varint,5,opt,name=isMuted,proto3" json:"isMuted,omitempty"`
	IsTrigerSwd   bool                   `protobuf:"varint,6,opt,name=isTrigerSwd,proto3" json:"isTrigerSwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendClientInfoPb) Reset() {
	*x = SendClientInfoPb{}
	mi := &file_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendClientInfoPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendClientInfoPb) ProtoMessage() {}

func (x *SendClientInfoPb) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendClientInfoPb.ProtoReflect.Descriptor instead.
func (*SendClientInfoPb) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{1}
}

func (x *SendClientInfoPb) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *SendClientInfoPb) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendClientInfoPb) GetUserTags() string {
	if x != nil {
		return x.UserTags
	}
	return ""
}

func (x *SendClientInfoPb) GetIsAnchor() bool {
	if x != nil {
		return x.IsAnchor
	}
	return false
}

func (x *SendClientInfoPb) GetIsMuted() bool {
	if x != nil {
		return x.IsMuted
	}
	return false
}

func (x *SendClientInfoPb) GetIsTrigerSwd() bool {
	if x != nil {
		return x.IsTrigerSwd
	}
	return false
}

var File_msg_proto protoreflect.FileDescriptor

const file_msg_proto_rawDesc = "" +
	"\n" +
	"\tmsg.proto\x12\x03sdk\"\x82\x02\n" +
	"\tMessagePb\x125\n" +
	"\n" +
	"sendClient\x18\x01 \x01(\v2\x15.sdk.SendClientInfoPbR\n" +
	"sendClient\x12\x1c\n" +
	"\tmessageId\x18\x02 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x05 \x01(\tR\x04data\x12\x16\n" +
	"\x06liveId\x18\x06 \x01(\tR\x06liveId\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x120\n" +
	"\bpriority\x18\b \x01(\x0e2\x14.sdk.MessagePriorityR\bpriority\"\xba\x01\n" +
	"\x10SendClientInfoPb\x12\x1a\n" +
	"\bnickName\x18\x01 \x01(\tR\bnickName\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\buserTags\x18\x03 \x01(\tR\buserTags\x12\x1a\n" +
	"\bisAnchor\x18\x04 \x01(\bR\bisAnchor\x12\x18\n" +
	"\aisMuted\x18\x05 \x01(\bR\aisMuted\x12 \n" +
	"\visTrigerSwd\x18\x06 \x01(\bR\visTrigerSwd*$\n" +
	"\x0fMessagePriority\x12\a\n" +
	"\x03LOW\x10\x00\x12\b\n" +
	"\x04HIGH\x10\x01B\aZ\x05./sdkb\x06proto3"

var (
	file_msg_proto_rawDescOnce sync.Once
	file_msg_proto_rawDescData []byte
)

func file_msg_proto_rawDescGZIP() []byte {
	file_msg_proto_rawDescOnce.Do(func() {
		file_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msg_proto_rawDesc), len(file_msg_proto_rawDesc)))
	})
	return file_msg_proto_rawDescData
}

var file_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_msg_proto_goTypes = []any{
	(MessagePriority)(0),     // 0: sdk.MessagePriority
	(*MessagePb)(nil),        // 1: sdk.MessagePb
	(*SendClientInfoPb)(nil), // 2: sdk.SendClientInfoPb
}
var file_msg_proto_depIdxs = []int32{
	2, // 0: sdk.MessagePb.sendClient:type_name -> sdk.SendClientInfoPb
	0, // 1: sdk.MessagePb.priority:type_name -> sdk.MessagePriority
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_msg_proto_init() }
func file_msg_proto_init() {
	if File_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msg_proto_rawDesc), len(file_msg_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_proto_goTypes,
		DependencyIndexes: file_msg_proto_depIdxs,
		EnumInfos:         file_msg_proto_enumTypes,
		MessageInfos:      file_msg_proto_msgTypes,
	}.Build()
	File_msg_proto = out.File
	file_msg_proto_goTypes = nil
	file_msg_proto_depIdxs = nil
}
